name: clang-format linter

on:
  push:
    branches:
      - master
    tags:
       - '*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@master
