name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@master
