name: clang-format linter

on:
  push:
    branches:
      - master
    tags:
       - '*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@master
      with:
        itk-branch: master
