name: WebAssembly

on: [push,pull_request]

jobs:
  build-wasm:
    name: "build-test-wasm"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test WASI
      run: |
        npm run test:wasi

    - name: Build TypeScript, JavaScript package
      run: |
        cd wasm/typescript
        npm install
        npm run build

    - name: Test Node.js interface
      run: |
        cd wasm/typescript
        npm run test:node

    - name: Test Browser interface, Chrome
      uses: cypress-io/github-action@v5
      with:
        working-directory: ./wasm/typescript
        browser: chrome
        start: npm start

    - name: Test Browser interface, Firefox
      uses: cypress-io/github-action@v5
      with:
        working-directory: ./wasm/typescript
        browser: firefox
        start: npm start

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: wasm/typescript/cypress/screenshots

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: wasm/typescript/cypress/videos