name: WebAssembly

on:
  push:
    branches:
      - master
    tags:
       - '*'
  pull_request:
    branches:
      - master

jobs:
  build-wasm:
    name: "build-test-wasm"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v3.5.3

    - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: '18'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test WASI
      run: |
        npm run test:wasi

    - name: Build TypeScript, JavaScript package
      run: |
        cd wasm/typescript
        npm install
        npm run build

    - name: Test Node.js interface
      run: |
        cd wasm/typescript
        npm run test:node

    - name: Test Browser interface, Chrome
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./wasm/typescript
        browser: chrome
        start: npm start

    - name: Test Browser interface, Firefox
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./wasm/typescript
        browser: firefox
        start: npm start

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: wasm/typescript/cypress/screenshots

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: wasm/typescript/cypress/videos